version: '3.8'
services:
  dev-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'nest-test'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    restart: always
volumes:
  my-db: